version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: 2048m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  api:
    container_name: api-container
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    # TODO remove volumes, as it does not honor .dockerignore.
    # simplifies development
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - elasticsearch
    networks:
      - es-net

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  es-net:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
    driver_opts:
      type: none
      device: ./elasticsearch-infra/elasticsearch/data/
      o: bind
