# Generated by Django 4.1.8 on 2023-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('min_of_participants', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('num_of_ratings', models.PositiveIntegerField(default=0)),
                ('language_offered', models.CharField(max_length=255)),
            ],
        ),
    ]
