name: test
on: [push]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
       # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.2"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        env:
          pythonLocation: ${{ env.PYTHON }}
          PATH: ${{ env.PATH }}:${{ env.PYTHON }}/bin
        with:
          command: run pipenv run pytest # Run custom `test` command defined in the `[scripts]` block of Pipfile
