name: test
on: [push]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: $ {{ github.ref }}
      
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test # Run custom `test` command defined in the `[scripts]` block of Pipfile
